/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorgui;

/**
 *
 * @author ASUS
 */
public class Kalkulator extends javax.swing.JFrame {
String angka ;
    double total, bilangansatu, bilangandua;
    boolean negative,positive;
    
    int pilihan;
    /**
     * Creates new form Latihan05
     */
    public Kalkulator() {
        initComponents();
         angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        layar = new javax.swing.JTextField();
        plusminus = new javax.swing.JButton();
        a7 = new javax.swing.JButton();
        a8 = new javax.swing.JButton();
        a9 = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        a6 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        a0 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bagi = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\Rain Meter\\61784598_p0.jpg")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\Rain Meter\\69905729_p0_master1200.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        getContentPane().setLayout(null);

        layar.setEditable(false);
        layar.setBackground(new java.awt.Color(153, 153, 153));
        layar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        layar.setToolTipText("");
        layar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layarActionPerformed(evt);
            }
        });
        getContentPane().add(layar);
        layar.setBounds(20, 50, 320, 80);

        plusminus.setBackground(new java.awt.Color(153, 153, 153));
        plusminus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        plusminus.setText("±");
        plusminus.setToolTipText("");
        plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusActionPerformed(evt);
            }
        });
        getContentPane().add(plusminus);
        plusminus.setBounds(10, 510, 70, 70);

        a7.setBackground(new java.awt.Color(153, 153, 153));
        a7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a7.setText("7");
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        getContentPane().add(a7);
        a7.setBounds(10, 240, 70, 70);

        a8.setBackground(new java.awt.Color(153, 153, 153));
        a8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a8.setText("8");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        getContentPane().add(a8);
        a8.setBounds(100, 240, 70, 70);

        a9.setBackground(new java.awt.Color(153, 153, 153));
        a9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a9.setText("9");
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        getContentPane().add(a9);
        a9.setBounds(190, 240, 70, 70);

        kurang.setBackground(new java.awt.Color(153, 153, 153));
        kurang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang);
        kurang.setBounds(290, 380, 60, 60);

        tambah.setBackground(new java.awt.Color(153, 153, 153));
        tambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(290, 450, 60, 60);

        samadengan.setBackground(new java.awt.Color(153, 153, 153));
        samadengan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(samadengan);
        samadengan.setBounds(290, 520, 60, 60);

        a6.setBackground(new java.awt.Color(153, 153, 153));
        a6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a6.setText("6");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        getContentPane().add(a6);
        a6.setBounds(190, 330, 70, 70);

        a3.setBackground(new java.awt.Color(153, 153, 153));
        a3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a3.setText("3");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(190, 420, 70, 70);

        a5.setBackground(new java.awt.Color(153, 153, 153));
        a5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a5.setText("5");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        getContentPane().add(a5);
        a5.setBounds(100, 330, 70, 70);

        a4.setBackground(new java.awt.Color(153, 153, 153));
        a4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a4.setText("4");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        getContentPane().add(a4);
        a4.setBounds(10, 330, 70, 70);

        a1.setBackground(new java.awt.Color(153, 153, 153));
        a1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a1.setText("1");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(10, 420, 70, 70);

        a2.setBackground(new java.awt.Color(153, 153, 153));
        a2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a2.setText("2");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2);
        a2.setBounds(100, 420, 70, 70);

        titik.setBackground(new java.awt.Color(153, 153, 153));
        titik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        getContentPane().add(titik);
        titik.setBounds(190, 510, 70, 70);

        pangkat.setBackground(new java.awt.Color(153, 153, 153));
        pangkat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pangkat.setText("^");
        pangkat.setToolTipText("");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        getContentPane().add(pangkat);
        pangkat.setBounds(150, 160, 60, 60);

        kali.setBackground(new java.awt.Color(153, 153, 153));
        kali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kali.setText("x");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(290, 310, 60, 60);

        delete.setBackground(new java.awt.Color(153, 153, 153));
        delete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        delete.setText("Exit");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(10, 160, 60, 60);

        persen.setBackground(new java.awt.Color(153, 153, 153));
        persen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        getContentPane().add(persen);
        persen.setBounds(290, 240, 60, 60);

        a0.setBackground(new java.awt.Color(153, 153, 153));
        a0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a0.setText("0");
        a0.setToolTipText("");
        a0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a0ActionPerformed(evt);
            }
        });
        getContentPane().add(a0);
        a0.setBounds(100, 510, 70, 70);

        jLabel4.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jLabel4.setText("CALCULATOR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 10, 180, 30);

        bagi.setBackground(new java.awt.Color(153, 153, 153));
        bagi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bagi.setText(":");
        bagi.setToolTipText("");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi);
        bagi.setBounds(220, 160, 60, 60);

        c2.setBackground(new java.awt.Color(153, 153, 153));
        c2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c2.setText("C");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(80, 160, 60, 60);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 160, 60, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\Rain Meter\\61784598_p0.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-890, -10, 1260, 830);

        setSize(new java.awt.Dimension(375, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
        // TODO add your handling code here:
        angka+="9";
        layar.setText(angka);
    }//GEN-LAST:event_a9ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
        angka+="4";
        layar.setText(angka);
    }//GEN-LAST:event_a4ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        // TODO add your handling code here:
        angka+="7";
        layar.setText(angka);
    }//GEN-LAST:event_a7ActionPerformed

    private void layarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_layarActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        // TODO add your handling code here:
        angka+="8";
        layar.setText(angka);
    }//GEN-LAST:event_a8ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
        angka+="5";
        layar.setText(angka);
    }//GEN-LAST:event_a5ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
        angka+="6";
        layar.setText(angka);
    }//GEN-LAST:event_a6ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
        angka+="1";
        layar.setText(angka);
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
        angka+="2";
        layar.setText(angka);
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
        angka+="3";
        layar.setText(angka);
    }//GEN-LAST:event_a3ActionPerformed

    private void a0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a0ActionPerformed
        // TODO add your handling code here:
        angka+="0";
        layar.setText(angka);
    }//GEN-LAST:event_a0ActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
        switch(pilihan){
            
            case 1:
                bilangandua=Double.parseDouble(angka);
                total = bilangansatu/bilangandua;
                angka = Double.toString(total);
                layar.setText(angka);
                break;
            case 2:
                bilangandua=Double.parseDouble(angka);
                total = bilangansatu+bilangandua;
                angka = Double.toString(total);
                layar.setText(angka);
                break;
            case 3:
                bilangandua=Double.parseDouble(angka);
                total = bilangansatu-bilangandua;
                angka = Double.toString(total);
                layar.setText(angka);
                break;
            case 4:
                bilangandua=Double.parseDouble(angka);
                total = bilangansatu*bilangandua;
                angka = Double.toString(total);
                layar.setText(angka);
                break;
            case 5:
            bilangandua=Double.parseDouble(angka);
                total = Math.pow(bilangansatu,bilangandua);
                angka = Double.toString(total);
                layar.setText(angka);
                break;
            case 6:
                total = bilangansatu/100;
                angka = Double.toString(total);
                layar.setText(angka);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_samadenganActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        // TODO add your handling code here:
         bilangansatu = Double.parseDouble(angka);
        layar.setText("^");
        angka="";
        pilihan=5;
    }//GEN-LAST:event_pangkatActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("*");
        angka="";
        pilihan=4;
    }//GEN-LAST:event_kaliActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("-");
        angka="";
        pilihan=3;
    }//GEN-LAST:event_kurangActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
         bilangansatu = Double.parseDouble(angka);
        layar.setText("+");
        angka="";
        pilihan =2;
    }//GEN-LAST:event_tambahActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("%");
        angka="";
        pilihan = 6;
    }//GEN-LAST:event_persenActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        // TODO add your handling code here:
        angka +=".";
        
        Double titik = Double.parseDouble(angka);
                layar.setText(angka+".");
    }//GEN-LAST:event_titikActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("/");
        angka="";
        pilihan = 1;
    }//GEN-LAST:event_bagiActionPerformed

    private void plusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusActionPerformed
        // TODO add your handling code here:
        if(!angka.contains("-"))
        angka = "-"+angka;
        
        else
        
        angka =angka.substring(1,angka.length());
        layar.setText(angka);
    }//GEN-LAST:event_plusminusActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_deleteActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        layar.setText("");
        bilangansatu=0;
        bilangandua=0;
        total=0;
        angka="";
    }//GEN-LAST:event_c2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        angka = angka.substring(0,angka.length()-1);
        layar.setText(angka);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a0;
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton a5;
    private javax.swing.JButton a6;
    private javax.swing.JButton a7;
    private javax.swing.JButton a8;
    private javax.swing.JButton a9;
    private javax.swing.JButton bagi;
    private javax.swing.JButton c2;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JTextField layar;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton persen;
    private javax.swing.JButton plusminus;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton titik;
    // End of variables declaration//GEN-END:variables
}
